# Generated by Django 3.1.7 on 2021-02-28 18:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterModelTable(
            name='user',
            table='bb_user',
        ),
    ]
