# Generated by Django 3.1.7 on 2021-04-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0003_user_strategy_pair_daily_balance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_strategy_pair',
            name='no_of_failed_attempts',
            field=models.IntegerField(default=0, verbose_name='Number of Failed Attempts'),
        ),
    ]
