# Generated by Django 3.1.7 on 2021-02-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0003_auto_20210228_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='temp_id',
            new_name='user_id',
        ),
    ]
