# Generated by Django 3.1.7 on 2021-02-28 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0004_auto_20210228_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('exchange_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Exchange Name')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='Display Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_on')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('strategy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Strategy Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_on')),
            ],
        ),
        migrations.CreateModel(
            name='User_Strategy_Account',
            fields=[
                ('user_strategy_account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, verbose_name='API Key'))),
                ('api_secret', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, verbose_name='API Secret'))),
                ('sub_account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub-account Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_on')),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.exchange')),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.strategy')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Strategy_Pair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pair', models.CharField(blank=True, max_length=50, verbose_name='Pair')),
                ('initial_first_symbol_balance', models.FloatField(blank=True, null=True, verbose_name='Initial First Symbol Balance')),
                ('initial_second_symbol_balance', models.FloatField(blank=True, null=True, verbose_name='Initial First Symbol Balance')),
                ('current_currency', models.CharField(blank=True, max_length=50, verbose_name='Current Currency')),
                ('current_currency_balance', models.FloatField(blank=True, null=True, verbose_name='Current Currency Balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified_on')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_on')),
                ('user_strategy_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.user_strategy_account')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy_Supported_Pairs',
            fields=[
                ('pair_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pair', models.CharField(blank=True, max_length=50, verbose_name='Pair')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_on')),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.strategy')),
            ],
        ),
        migrations.CreateModel(
            name='Strategies_Suggested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_utc', models.DateTimeField(verbose_name='start_time_utc')),
                ('target_currency', models.CharField(blank=True, max_length=50, verbose_name='Target Currency')),
                ('tick', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Tick')),
                ('pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.strategy_supported_pairs')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('pair', models.CharField(blank=True, max_length=50, verbose_name='Pair')),
                ('order_type', models.CharField(blank=True, max_length=50, verbose_name='Order Type')),
                ('currency_price', models.IntegerField(default=0, verbose_name='Currency Price')),
                ('order_cost', models.IntegerField(default=0, verbose_name='Order Cost')),
                ('order_status', models.CharField(blank=True, max_length=50, verbose_name='Order Status')),
                ('order_side', models.CharField(blank=True, max_length=50, verbose_name='Order Side')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified_on')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_on')),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.exchange')),
                ('user_strategy_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.user_strategy_account')),
            ],
        ),
    ]
