# Generated by Django 3.1.7 on 2021-04-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0005_exchange_sign_up_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_exchange_account',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Exchange Account Name'),
        ),
    ]
