# Generated by Django 3.1.7 on 2021-03-03 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0005_exchange_orders_strategies_suggested_strategy_strategy_supported_pairs_user_strategy_account_user_st'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Exchange_Account',
            fields=[
                ('user_exchange_account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, verbose_name='API Key'))),
                ('api_secret', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, verbose_name='API Secret'))),
                ('sub_account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub-account Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified_on')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_on')),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.exchange')),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.strategy')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_strategy_account',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='user_strategy_account',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='user_strategy_account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_strategy_pair',
            name='user_strategy_account',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='User_Strategy_Account',
        ),
        migrations.DeleteModel(
            name='User_Strategy_Pair',
        ),
    ]
