# Generated by Django 3.1.7 on 2021-05-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0006_auto_20210420_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='size_symbol',
            field=models.CharField(blank=True, max_length=50, verbose_name='Size Symbol'),
        ),
    ]
