# Generated by Django 3.1.7 on 2021-03-08 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0007_user_exchange_account_api_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Strategy_Pair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pair', models.CharField(blank=True, max_length=50, verbose_name='Pair')),
                ('initial_first_symbol_balance', models.FloatField(blank=True, null=True, verbose_name='Initial First Symbol Balance')),
                ('initial_second_symbol_balance', models.FloatField(blank=True, null=True, verbose_name='Initial Second Symbol Balance')),
                ('current_currency', models.CharField(blank=True, max_length=50, verbose_name='Current Currency')),
                ('current_currency_balance', models.FloatField(blank=True, null=True, verbose_name='Current Currency Balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified_on')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_on')),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.strategy')),
                ('user_exchange_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.user_exchange_account')),
            ],
        ),
    ]
