# Generated by Django 3.1.7 on 2021-03-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0009_user_strategy_pair_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_exchange_account',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Exchange Account Name'),
        ),
    ]
