# Generated by Django 3.1.7 on 2021-03-13 15:39

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0010_user_exchange_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('pair_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, max_length=50, verbose_name='Symbol')),
                ('ticker_1', models.CharField(blank=True, max_length=50, verbose_name='Ticker 1')),
                ('ticker_2', models.CharField(blank=True, max_length=50, verbose_name='Ticker 2')),
                ('ticker_1_min_value', models.FloatField(blank=True, null=True, verbose_name='Ticker 1 Min Value')),
                ('ticker_2_min_value', models.FloatField(blank=True, null=True, verbose_name='Ticker 2 Min Value')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_on')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_exchange_account',
            name='strategy',
        ),
    ]
