# Generated by Django 3.1.7 on 2021-03-13 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0011_auto_20210313_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy_supported_pairs',
            old_name='pair_id',
            new_name='strategy_pair_id',
        ),
        migrations.AlterField(
            model_name='strategy_supported_pairs',
            name='pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.pairs'),
        ),
    ]
