# Generated by Django 3.1.7 on 2021-03-19 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0012_auto_20210313_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('market', models.CharField(blank=True, max_length=50, verbose_name='Market')),
                ('side', models.CharField(blank=True, max_length=50, verbose_name='Side')),
                ('size', models.IntegerField(default=0, verbose_name='Order Size')),
                ('filled', models.IntegerField(default=0, verbose_name='Filled')),
                ('filled_price', models.IntegerField(default=0, verbose_name='Filled Price')),
                ('fee', models.IntegerField(default=0, verbose_name='Fee')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified_on')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_on')),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.exchange')),
                ('user_exchange_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.user_exchange_account')),
            ],
        ),
    ]
