# Generated by Django 3.1.7 on 2021-03-19 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0013_auto_20210319_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user_exchange_account',
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_strategy_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.user_strategy_pair'),
        ),
    ]
