# Generated by Django 3.1.7 on 2021-03-24 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0015_auto_20210319_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_connected',
            field=models.BooleanField(default=False, verbose_name='Connected'),
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=1, verbose_name='Story Stage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
