# Generated by Django 3.1.7 on 2021-03-26 18:32

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0016_auto_20210324_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_exchange_account',
            name='api_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, unique=True, verbose_name='API Key')),
        ),
        migrations.AlterField(
            model_name='user_exchange_account',
            name='api_secret',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, unique=True, verbose_name='API Secret')),
        ),
    ]
