# Generated by Django 3.1.7 on 2021-03-26 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0017_auto_20210326_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_exchange_account',
            name='api_key',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, verbose_name='API Key')),
        ),
        migrations.AlterField(
            model_name='user_exchange_account',
            name='api_secret',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, verbose_name='API Secret')),
        ),
        migrations.AlterField(
            model_name='user_exchange_account',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Exchange Account Name'),
        ),
    ]
