# Generated by Django 3.1.7 on 2021-03-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0018_auto_20210326_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='fee',
            field=models.FloatField(default=0, verbose_name='Fee'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='filled',
            field=models.FloatField(default=0, verbose_name='Filled'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='filled_price',
            field=models.FloatField(default=0, verbose_name='Filled Price'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='size',
            field=models.FloatField(default=0, verbose_name='Order Size'),
        ),
    ]
