# Generated by Django 3.1.7 on 2021-04-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0020_user_strategy_pair_daily_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_strategy_pair_daily_balance',
            name='ticker_1_balance',
        ),
        migrations.RemoveField(
            model_name='user_strategy_pair_daily_balance',
            name='ticker_2_balance',
        ),
        migrations.AddField(
            model_name='user_strategy_pair_daily_balance',
            name='hodl_value',
            field=models.FloatField(default=0, verbose_name='HODL Value'),
        ),
        migrations.AddField(
            model_name='user_strategy_pair_daily_balance',
            name='price',
            field=models.FloatField(default=0, verbose_name='Pair Price'),
        ),
        migrations.AddField(
            model_name='user_strategy_pair_daily_balance',
            name='strategy_value',
            field=models.FloatField(default=0, verbose_name='Strategy Value'),
        ),
    ]
