# Generated by Django 3.1.7 on 2021-04-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0021_auto_20210410_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange_Supported_Pairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.exchange')),
                ('pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.pairs')),
            ],
        ),
    ]
