# Generated by Django 3.1.7 on 2021-04-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0022_exchange_supported_pairs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
